#if !canImport(ObjectiveC)
import XCTest

extension HTTPResponseDateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPResponseDateTests = [
        ("testAsctimeTimestampParsing", testAsctimeTimestampParsing),
        ("testMalformedTimestampParsing", testMalformedTimestampParsing),
        ("testRFC1123TimestampParsing", testRFC1123TimestampParsing),
        ("testRFC850TimestampParsing", testRFC850TimestampParsing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HTTPResponseDateTests.__allTests__HTTPResponseDateTests),
    ]
}
#endif
